# Generated by Django 4.0.4 on 2022-05-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointTypes',
        ),
    ]
