# Generated by Django 4.0.3 on 2022-05-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointtypes',
            options={'verbose_name': 'Вид заведения', 'verbose_name_plural': 'Виды заведений'},
        ),
        migrations.AlterField(
            model_name='pointtypes',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Виды заведений'),
        ),
    ]
