# Generated by Django 4.0.3 on 2022-05-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_pointtypes_options_alter_pointtypes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=200, verbose_name='Короткое название')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное название')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField()),
                ('place_chords_x', models.FloatField(verbose_name='Кордината Х')),
                ('place_chords_y', models.FloatField(verbose_name='Кордината Y')),
                ('point_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.pointtypes', verbose_name='Тип заведения')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
    ]
