# Generated by Django 4.0.3 on 2022-05-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
