# Generated by Django 4.0.3 on 2022-05-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='room',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
